language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - npm install -g @angular/cli

script:
  - yarn lint
  - yarn build-prod
